export const auth = {
  login: {
    title: "Bem-vindo de volta",
    subtitle: "Entre com suas credenciais para acessar",
    emailLabel: "Email",
    emailPlaceholder: "seu@email.com",
    passwordLabel: "Senha",
    passwordPlaceholder: "••••••••",
    submitButton: "Entrar",
    submitting: "Entrando...",
    forgotPassword: "Esqueci minha senha",
    toasts: {
      success: "Login realizado com sucesso!",
      invalidCredentials: "Email ou senha incorretos",
      emailNotConfirmed: "Email não confirmado. Verifique sua caixa de entrada.",
      generic: "Ocorreu um erro. Tente novamente.",
    },
  },

  forgotPassword: {
    pageTitle: "Esqueceu a senha?",
    pageSubtitle: "Informe seu email e enviaremos um link para redefinir sua senha.",
    title: "Redefinir senha",
    subtitle: "Digite o email da sua conta. Enviaremos um link para criar uma nova senha.",
    emailLabel: "Email",
    emailPlaceholder: "seu@email.com",
    submitButton: "Enviar link",
    submitting: "Enviando...",
    backToLogin: "Voltar ao login",
    sentTitle: "Email enviado",
    sentMessage:
      "Se existir uma conta com esse email, você receberá um link em instantes. Verifique a caixa de entrada e o spam.",
    toasts: {
      success: "Link enviado! Verifique seu email.",
      generic: "Ocorreu um erro. Tente novamente.",
    },
  },

  resetPassword: {
    pageTitle: "Nova senha",
    pageSubtitle: "Defina uma nova senha para acessar sua conta.",
    title: "Definir nova senha",
    passwordLabel: "Nova senha",
    passwordPlaceholder: "••••••••",
    confirmLabel: "Confirmar senha",
    submitButton: "Salvar nova senha",
    submitting: "Salvando...",
    backToLogin: "Voltar ao login",
    requestNewLink: "Solicitar novo link",
    expiredTitle: "Link expirado ou inválido",
    expiredMessage: "Solicite um novo link de redefinição de senha na página de login.",
    requirements: {
      title: "Requisitos da senha:",
      minLength: "Mínimo de 8 caracteres",
      uppercase: "Pelo menos uma letra maiúscula (A-Z)",
      lowercase: "Pelo menos uma letra minúscula (a-z)",
      number: "Pelo menos um número (0-9)",
      special: "Pelo menos um caractere especial (!@#$%^&*)",
    },
    toasts: {
      success: "Senha alterada. Faça login com a nova senha.",
      expiredLink: "Link expirado ou inválido. Solicite um novo link.",
      minLength: "A senha deve ter no mínimo 8 caracteres.",
      uppercase: "A senha deve conter pelo menos uma letra maiúscula.",
      lowercase: "A senha deve conter pelo menos uma letra minúscula.",
      number: "A senha deve conter pelo menos um número.",
      special: "A senha deve conter pelo menos um caractere especial (!@#$%^&*).",
      passwordMismatch: "As senhas não coincidem.",
      generic: "Ocorreu um erro. Tente novamente.",
    },
  },

  changePassword: {
    title: "Alterar senha",
    securityNotice: "Por segurança, você precisa alterar sua senha temporária antes de continuar.",
    currentPasswordLabel: "Senha atual",
    newPasswordLabel: "Nova senha",
    confirmPasswordLabel: "Confirmar nova senha",
    submitButton: "Alterar senha",
    submitting: "Alterando...",
    toasts: {
      success: "Senha alterada com sucesso.",
      currentPasswordWrong: "Senha atual incorreta.",
      passwordMismatch: "As senhas não coincidem.",
      newPasswordMinLength: "Nova senha deve ter no mínimo 6 caracteres.",
      confirmPasswordRequired: "Confirme a nova senha.",
      generic: "Ocorreu um erro. Tente novamente.",
    },
  },
} as const;
