export const classes = {
  view: {
    title: "Aulas",
    subtitle: "Registro de aulas e acompanhamento",
    newButton: "Nova Aula",
    packageButton: "Novo Pacote",
    statTotal: "Total",
    statAttended: "Realizadas",
    statPending: "Pendentes",
    statEvaluationPending: "Avaliação Pendente",
    statPackage: "Pacote",
    errorLoading: "Erro ao carregar registros de aula. Tente novamente.",
  },

  table: {
    colStatus: "Status",
    colStudent: "Aluno",
    colInfo: "Informações",
    colTitle: "Título da aula",
    colDate: "Data",
    colDuration: "Duração",
    colGrade: "Nota",
    colFinancial: "Financeiro",
    colActions: "Ações",
    noResults: "Nenhum resultado",
    noResultsHint: "Ajuste os filtros acima ou limpe a busca",
    prev: "Anterior",
    next: "Próximo",
  },

  tableRow: {
    noAttendance: "Não compareceu",
    noCharge: "Sem cobrança",
    statusPaid: "Pago",
    statusPending: "Pendente",
    statusOverdue: "Atrasado",
    statusValidating: "Validando",
    evaluate: "Avaliar",
    update: "Atualizar",
    edit: "Editar",
    delete: "Excluir",
    viewDetails: "Ver detalhes",
    noTeacher: "Sem professor",
    editedAt: "Editado em",
    packageMonthly: "Pacote mensal",
    packageClasses: "aula(s)",
  },

  cardView: {
    grade: "Nota",
    noAttendance: "Não compareceu",
    noCharge: "Sem cobrança",
    noResults: "Nenhum resultado",
    noResultsHint: "Ajuste os filtros acima ou limpe a busca",
    prev: "Anterior",
    next: "Próximo",
    update: "Atualizar",
    evaluate: "Avaliar",
    edit: "Editar",
    delete: "Excluir",
    viewDetails: "Ver detalhes",
  },

  logFormDialog: {
    titleNew: "Nova Aula",
    titleEdit: "Editar aula",
    studentLabel: "Aluno *",
    studentPlaceholder: "Selecione um aluno",
    dateLabel: "Data da aula *",
    datePlaceholder: "dd/mm/aaaa",
    startTimeLabel: "Início",
    endTimeLabel: "Fim",
    titleFieldLabel: "Título (opcional)",
    feedbackLabel: "Feedback (opcional)",
    observationsLabel: "Observações (opcional)",
    gradeLabel: "Nota (0–100)",
    financialSectionTitle: "Cobrança",
    noChargeLabel: "Sem cobrança",
    amountLabel: "Valor *",
    dueDateLabel: "Vencimento *",
    paymentMethodLabel: "Forma de pagamento",
    descriptionLabel: "Descrição",
    submitButton: "Salvar",
    submitting: "Salvando...",
    cancel: "Cancelar",
    toasts: {
      success: "Aula registrada com sucesso!",
      successWithPayment: "Aula e cobrança registradas com sucesso!",
      successEdit: "Aula atualizada com sucesso!",
      successDelete: "Registro removido com sucesso!",
      error: "Erro ao salvar aula.",
    },
  },

  logFinancialSection: {
    noCharge: "Sem cobrança",
    sectionTitleNew: "Dados da Cobrança *",
    sectionTitleEdit: "Dados da Cobrança",
    futureClassHint:
      "Para aula agendada: a cobrança fica em aberto; presença e feedback podem ser marcados depois.",
    calculatedValue: "Valor calculado:",
    noHourlyRate:
      "Aluno sem valor/hora cadastrado. Informe o valor manualmente.",
    noTimeRange: "Informe início e término para calcular o valor.",
    amountLabel: "Valor (R$) *",
    amountLabelEdit: "Valor (R$)",
    dueDateLabel: "Vencimento *",
    dueDateLabelEdit: "Vencimento",
    selectDate: "Selecione a data",
    descriptionLabel: "Descrição",
    descriptionPlaceholder: "Aula de inglês - Janeiro",
    descriptionHint: 'Se não preenchido, será "Aula do dia [data]"',
    paymentMethodLabel: "Método de Pagamento",
    paymentMethodPlaceholder: "Selecione (opcional)",
    pix: "PIX",
    card: "Cartão",
    cash: "Dinheiro",
    transfer: "Transferência",
    other: "Outro",
    editDateHint:
      "Alterar a data da aula não altera o vencimento automaticamente; edite aqui se quiser.",
  },

  packageDialog: {
    title: "Cadastrar pacote de aulas",
    teacherLabel: "Professor *",
    teacherPlaceholder: "Selecione um professor",
    studentLabel: "Aluno *",
    studentPlaceholder: "Selecione um aluno",
    noCharge: "Sem cobrança",
    cancel: "Cancelar",
    submitting: "Cadastrando...",
    submitButton: (count: number) => `Cadastrar ${count} aula(s)`,
    description: "Registre múltiplas aulas de uma vez.",
    submitButtonBase: "Salvar pacote",
    modeFixed: "Horário fixo",
    modeDynamic: "Aulas individuais",
    generateButton: "Gerar aulas do mês",
    slotListTitle: "Aulas geradas",
    slotListTitleDynamic: "Aulas individuais",
    addSlotButton: "Adicionar",
    slotDateLabel: "Data",
    slotStartLabel: "Início",
    slotEndLabel: "Término",
    toasts: {
      selectMonth: "Selecione o mês e o ano.",
      selectWeekday: "Selecione pelo menos um dia da semana.",
      invalidTime: "Informe o horário de início e término.",
      endTimeBeforeStart: "Horário de término deve ser posterior ao início.",
      noDatesFound: "Nenhuma data encontrada para o mês e dias selecionados.",
      generated: (count: number, month: string, year: number) =>
        `${count} aula(s) gerada(s) para ${month}/${year}.`,
      selectPaymentMethod: "Selecione o método de pagamento.",
      success: "Pacote cadastrado com sucesso!",
      error: "Erro ao cadastrar pacote.",
    },
  },

  postClassDialog: {
    title: "Avaliar aula",
    attendanceLabel: "Comparecimento",
    attended: "Compareceu",
    absent: "Faltou",
    gradeLabel: "Nota (0–100)",
    feedbackLabel: "Feedback",
    feedbackPlaceholder: "Observações sobre a aula...",
    chargeAbsenceLabel: "Cobrar esta falta",
    refundLabel: "Extornar pagamento",
    refundDescription:
      "O pagamento será marcado como extornado (devolvido ao aluno)",
    cancel: "Cancelar",
    save: "Salvar",
    description: "Registre o resultado e feedback da aula.",
    submitButton: "Salvar",
    submitting: "Salvando...",
    toasts: {
      evaluationError: "Erro ao registrar avaliação. Tente novamente.",
      success: "Avaliação registrada com sucesso!",
    },
  },

  historyList: {
    emptyMessage: "Nenhuma aula registrada",
  },

  filters: {
    searchLabel: "Busca",
    searchPlaceholder: "Buscar por título ou aluno...",
    statusLabel: "Status",
    statusOpen: "Em aberto",
    statusAll: "Todos",
    statusScheduled: "Agendada",
    statusPending: "Pendente",
    statusDone: "Concluída",
    studentLabel: "Aluno",
    studentAll: "Todos os alunos",
    sortLabel: "Ordenar",
    sortRecent: "Mais recente",
    sortOldest: "Mais antigo",
    moreFilters: "Mais Filtros",
    clear: "Limpar",
    teacherLabel: "Professor",
    teacherAll: "Todos os professores",
    typeLabel: "Tipo",
    typeAll: "Todos",
    typePackage: "Pacote",
    typeIndividual: "Individual",
    periodLabel: "Período",
    periodAll: "Todos",
    periodWeek: "Semana",
    periodMonth: "Mês",
    period3Months: "3 meses",
    monthLabel: "Mês",
    yearLabel: "Ano",
    weekdaysLabel: "Dias da semana",
  },

  deleteDialog: {
    title: "Confirmar exclusão",
    description: (studentName: string, date: string) =>
      `Tem certeza que deseja excluir o registro de aula de ${studentName} do dia ${date}?`,
    warningPaid:
      "Esta aula possui uma cobrança já paga. A exclusão da aula também exclui a cobrança. Deseja excluir mesmo assim?",
    warningLinked:
      "⚠️ Esta aula possui uma cobrança vinculada que também será afetada.",
    confirmButton: "Excluir",
    deleting: "Excluindo...",
    toasts: {
      success: "Aula excluída com sucesso!",
      error: "Erro ao excluir aula.",
    },
  },

  detailSheet: {
    title: "Detalhes da Aula",
    studentSection: "Aluno",
    financialSection: "Cobrança",
    feedbackSection: "Feedback",
    observationsSection: "Observações",
  },

  emptyState: {
    title: "Nenhuma aula encontrada",
    description: "Registre a primeira aula para começar.",
    actionLabel: "Nova Aula",
  },

  validation: {
    studentRequired: "Selecione um aluno",
    dateRequired: "Informe a data da aula",
    dateFormat: "Formato deve ser dd/mm/aaaa",
    dateInvalid: "Data inválida",
    dateMinYear: "Informe uma data de 2026 em diante",
    timeFormat: "Formato HH:mm",
    endTimeAfterStart: "Horário de fim deve ser após o início",
    gradeRange: "Nota deve ser entre 0 e 100",
    amountRequired: "Informe o valor",
    dueDateRequired: "Informe a data de vencimento",
    dueDateFormat: "Formato deve ser dd/mm/aaaa",
    dueDateInvalid: "Data inválida",
    classLogRequired: "Selecione uma aula para vincular",
    observationsMaxLength: "Máximo 1000 caracteres",
    teacherRequired: "Selecione um professor",
    studentRequired2: "Selecione um aluno.",
  },
} as const;
