export const common = {
  actions: {
    save: "Salvar",
    saving: "Salvando...",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Excluir",
    deleting: "Excluindo...",
    edit: "Editar",
    close: "Fechar",
    back: "Voltar",
    loading: "Carregando...",
    sending: "Enviando...",
    search: "Buscar",
    filter: "Filtrar",
    clear: "Limpar",
    add: "Adicionar",
    create: "Criar",
    update: "Atualizar",
    view: "Visualizar",
    download: "Baixar",
    copy: "Copiar",
    copied: "Copiado!",
    yes: "Sim",
    no: "Não",
    apply: "Aplicar",
  },

  status: {
    active: "Ativo",
    inactive: "Inativo",
    pending: "Pendente",
    paid: "Pago",
    overdue: "Vencido",
    cancelled: "Cancelado",
    completed: "Concluído",
    inProgress: "Em andamento",
    sent: "Enviada",
    delivered: "Entregue",
    corrected: "Corrigida",
    notDelivered: "Não entregue",
    pendingEvaluation: "Avaliação pendente",
    evaluated: "Avaliada",
  },

  errors: {
    generic: "Ocorreu um erro. Tente novamente.",
    network: "Erro de conexão. Verifique sua internet e tente novamente.",
    timeout: "A operação demorou muito. Tente novamente.",
    permissionDenied: "Você não tem permissão para realizar esta ação.",
    unauthorized: "Acesso não autorizado.",
    notFound: "Registro não encontrado.",
    duplicate: "Este registro já existe no sistema.",
    duplicateEmail: "Este email já está cadastrado.",
    duplicatePhone: "Este telefone já está cadastrado.",
    foreignKey: "Não é possível realizar esta operação devido a dependências.",
    validation: "Os dados fornecidos são inválidos.",
    fileTooLarge: "O arquivo é muito grande.",
    invalidFileType: "Tipo de arquivo não permitido.",
    gradeRange: "A nota deve estar entre 0 e 100.",
    sessionExpired: "Sua sessão expirou. Faça login novamente.",
  },

  table: {
    noResults: "Nenhum resultado encontrado.",
    showing: "Mostrando",
    of: "de",
    results: "resultados",
    page: "Página",
    previous: "Anterior",
    next: "Próxima",
    rowsPerPage: "Linhas por página",
    emptyState: "Nenhum registro encontrado.",
  },

  validation: {
    required: "Campo obrigatório.",
    emailInvalid: "Email inválido.",
    phoneInvalid: "Telefone inválido.",
    minLength: (n: number) => `Mínimo de ${n} caracteres.`,
    maxLength: (n: number) => `Máximo de ${n} caracteres.`,
    positiveNumber: "Deve ser um número positivo.",
    dateInvalid: "Data inválida.",
  },

  confirm: {
    deleteTitle: "Confirmar exclusão",
    deleteDescription: "Esta ação não pode ser desfeita.",
    irreversible: "Esta ação é irreversível.",
  },

  app: {
    name: "English School",
    copyright: (year: number) => `English School © ${year}`,
    tagline: "Manage your classes, track progress, and handle payments all in one place.",
    lgpd: "Conforme LGPD",
    developedBy: "Desenvolvido com",
    by: "por",
    developer: "Virtual Arrow",
    developerUrl: "https://virtualarrow.com.br",
  },

  toasts: {
    success: "Operação realizada com sucesso!",
    error: "Ocorreu um erro. Tente novamente.",
    saved: "Salvo com sucesso!",
    deleted: "Excluído com sucesso!",
    updated: "Atualizado com sucesso!",
    created: "Criado com sucesso!",
    copied: "Copiado!",
    loading: "Carregando...",
    processing: "Processando...",
  },

  aria: {
    tablePagination: "Paginação da tabela",
    previousPage: "Página anterior",
    nextPage: "Próxima página",
    closeDialog: "Fechar diálogo",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    loading: "Carregando",
    search: "Buscar",
    filter: "Filtrar",
    sort: "Ordenar",
    moreOptions: "Mais opções",
  },

  emptyStates: {
    noResults: "Nenhum resultado encontrado",
    noResultsHint: "Ajuste os filtros acima ou limpe a busca",
    noData: "Nenhum dado disponível",
    noRecords: "Nenhum registro encontrado",
    searchEmpty: (query: string) => `Não encontramos resultados para "${query}". Tente ajustar os filtros ou termos de busca.`,
    filterEmpty: "Ajuste os filtros para ver os resultados.",
  },

  placeholders: {
    search: "Buscar...",
    searchByName: "Buscar por nome...",
    searchByEmail: "Buscar por email...",
    searchByNameOrEmail: "Buscar por nome ou email...",
    select: "Selecione...",
    selectOption: "Selecione uma opção",
    optional: "(opcional)",
    none: "Nenhum",
    notAvailable: "Não disponível",
    notInformed: "Não informado",
  },

  labels: {
    all: "Todos",
    active: "Ativo",
    inactive: "Inativo",
    yes: "Sim",
    no: "Não",
    name: "Nome",
    email: "Email",
    phone: "Telefone",
    status: "Status",
    date: "Data",
    time: "Horário",
    description: "Descrição",
    observations: "Observações",
    actions: "Ações",
    details: "Detalhes",
    more: "Mais",
    less: "Menos",
    viewMore: "Ver mais",
    viewLess: "Ver menos",
    viewDetails: "Ver detalhes",
    editedAt: "Editado em",
    createdAt: "Criado em",
    updatedAt: "Atualizado em",
  },
} as const;
