export const common = {
  // Generic labels
  labels: {
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Deletar",
    edit: "Editar",
    add: "Adicionar",
    close: "Fechar",
    loading: "Carregando...",
    noData: "Nenhum dado disponível",
    email: "Email",
    name: "Nome",
    status: "Status",
    date: "Data",
    action: "Ação",
    actions: "Ações",
    // Extended labels
    all: "Todos",
    active: "Ativo",
    inactive: "Inativo",
    yes: "Sim",
    no: "Não",
    phone: "Telefone",
    time: "Horário",
    description: "Descrição",
    observations: "Observações",
    details: "Detalhes",
    more: "Mais",
    less: "Menos",
    viewMore: "Ver mais",
    viewLess: "Ver menos",
    viewDetails: "Ver detalhes",
    editedAt: "Editado em",
    createdAt: "Criado em",
    updatedAt: "Atualizado em",
    class: "Aula",
    teacherNotFound: "Professor não encontrado",
    noReason: "Sem motivo",
    sendDate: "Data de envio",
    dueDate: "Prazo de entrega",
    activityFile: "Arquivo da atividade",
    studentResponse: "Resposta do aluno",
    grade: "Nota",
    feedback: "Feedback",
    material: "Material",
    deliveredAt: "Entregue em",
    correctedAt: "Corrigida em",
    sentAt: "Enviada em",
    dueAt: "Prazo",
    noActivities: "Nenhuma atividade enviada.",
    selectTeacher: "Selecione um professor",
    optional: "(opcional)",
    feedbackCorrection: "Feedback / Correção",
    total: "Total",
    present: "Presenças",
    absence: "Faltas",
    classHistory: "Histórico de Aulas",
    noClassesMessage: "Nenhuma aula registrada",
    paid: "Pago",
    pending: "Pendente",
    overdue: "Atrasado",
    frequency: "Frequência",
    average: "Média",
    generalGrade: "Nota geral",
    classes: "aulas",
    personalInfo: "Informações Pessoais",
    birthDate: "Data de Nascimento",
    location: "Localização",
    countryStateCity: "País - Estado - Cidade",
    planAndBilling: "Plano de aulas e cobrança",
    hourlyRate: "Valor por hora",
    classesPerWeek: "Aulas por semana",
    monthlyTotal: "Total mensal",
    paymentDay: "Dia de pagamento",
    registeredAt: "Cadastro em",
    lastEdited: "Última edição em",
    origin: "Origem",
    notInformed: "Não informado",
    noPrivilege: "Sem privilégio",
    noName: "(sem nome)",
  },

  // Input placeholders
  placeholders: {
    search: "Buscar...",
    enterName: "Digite o nome",
    enterEmail: "Digite o email",
    enterPassword: "Digite a senha",
    // Extended placeholders
    searchByName: "Buscar por nome...",
    searchByEmail: "Buscar por email...",
    searchByNameOrEmail: "Buscar por nome ou email...",
    select: "Selecione...",
    selectOption: "Selecione uma opção",
    optional: "(opcional)",
    none: "Nenhum",
    notAvailable: "Não disponível",
    notInformed: "Não informado",
    period: "Período",
    answerHint: "Digite sua resposta aqui...",
    instructionsHint: "Instruções e observações...",
    classTopicHint: "Ex: Present Perfect - Unit 8",
    preClassNotesHint: "Notas pré-aula (opcional)...",
    gradeHint: "Ex: 85",
    classNotesHint: "Observações sobre a aula...",
    selectTeacher: "Selecione um professor",
    selectStudent: "Selecione um aluno",
    amount: "100,00",
    status: "Status",
    student: "Aluno",
    teacher: "Professor",
    sortBy: "Ordenar por",
    sorting: "Ordenação",
    teacherResponsible: "Professor responsável",
    type: "Tipo",
    additionalFilters: "Filtros adicionais",
    specialty: "Especialidade",
    privilege: "Privilégio",
    date: "dd/mm/aaaa",
    year: "Ano",
    email: "email@exemplo.com",
    phone: "(00) 00000-0000",
    password: "••••••••",
    payDay: "1 a 31",
  },

  // Button texts
  buttons: {
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Deletar",
    edit: "Editar",
    add: "Adicionar",
    submit: "Enviar",
    back: "Voltar",
    next: "Próximo",
    previous: "Anterior",
    // Extended buttons
    viewDetails: "Ver detalhes",
    viewFile: "Visualizar arquivo",
    viewPaymentHistory: "Ver histórico de pagamento",
    moreOptions: "Mais opções",
    waiting: "Aguardando",
    correct: "Corrigir",
    update: "Atualizar",
    viewWeb: "Visualizar na web",
    copyPix: "Copiar chave PIX",
    evaluate: "Avaliar",
    confirm: "Confirmar",
    create: "Criar",
    view: "Visualizar",
    download: "Baixar",
    copy: "Copiar",
    copied: "Copiado!",
    apply: "Aplicar",
    search: "Buscar",
    filter: "Filtrar",
    clear: "Limpar",
  },

  // Generic tooltips
  tooltips: {
    save: "Salvar alterações",
    cancel: "Cancelar operação",
    delete: "Deletar item",
    edit: "Editar item",
    add: "Adicionar novo item",
    close: "Fechar",
    // Extended tooltips
    viewDetails: "Ver detalhes",
    viewFile: "Visualizar arquivo",
    viewPaymentHistory: "Ver histórico de pagamento",
    moreOptions: "Mais opções",
    waiting: "Aguardando",
    correct: "Corrigir",
    update: "Atualizar",
    viewWeb: "Visualizar na web",
    copyPix: "Copiar chave PIX",
    evaluate: "Avaliar",
    administrator: "Administrador",
    teacher: "Professor",
    student: "Aluno",
    toggleSidebar: "Toggle Sidebar",
  },

  // Generic error messages
  errors: {
    required: "Campo obrigatório",
    invalidEmail: "Email inválido",
    passwordTooShort: "Senha muito curta",
    somethingWentWrong: "Algo deu errado",
    tryAgain: "Tente novamente",
    notFound: "Não encontrado",
    // Extended errors
    generic: "Ocorreu um erro. Tente novamente.",
    network: "Erro de conexão. Verifique sua internet e tente novamente.",
    timeout: "A operação demorou muito. Tente novamente.",
    permissionDenied: "Você não tem permissão para realizar esta ação.",
    unauthorized: "Acesso não autorizado.",
    duplicate: "Este registro já existe no sistema.",
    duplicateEmail: "Este email já está cadastrado.",
    duplicatePhone: "Este telefone já está cadastrado.",
    foreignKey: "Não é possível realizar esta operação devido a dependências.",
    validation: "Os dados fornecidos são inválidos.",
    fileTooLarge: "O arquivo é muito grande.",
    invalidFileType: "Tipo de arquivo não permitido.",
    gradeRange: "A nota deve estar entre 0 e 100.",
    sessionExpired: "Sua sessão expirou. Faça login novamente.",
    loadProfile: "Erro ao carregar seu perfil. Tente recarregar a página.",
    validateEmail: "Erro ao validar email. Tente novamente.",
    studentNotFound: "Aluno não encontrado",
    noEmail: "Sem email",
    selectTeacher: "Selecione um professor",
    selectStudent: "Selecione um aluno",
    loadingCities: "Carregando cidades...",
    errorBoundaryTitle: "Algo deu errado",
    errorBoundaryMessage: "Ocorreu um erro inesperado. Nossa equipe foi notificada e está trabalhando para resolver o problema.",
    errorBoundaryTechnical: "Detalhes técnicos (apenas em desenvolvimento)",
    errorBoundaryRetry: "Tentar novamente",
    errorBoundaryHome: "Voltar ao início",
    sectionErrorTitle: "Erro ao carregar seção",
    sectionErrorMessage: "Ocorreu um erro ao carregar esta seção. Tente recarregar ou continue usando outras partes do sistema.",
    sectionErrorReload: "Recarregar seção",
    phoneInvalid: "Telefone inválido.",
    dateInvalid: "Data inválida.",
  },

  // Accessibility labels
  aria: {
    loading: "Carregando",
    close: "Fechar",
    menu: "Menu",
    search: "Buscar",
    delete: "Deletar",
    edit: "Editar",
    // Extended aria
    tablePagination: "Paginação da tabela",
    previousPage: "Página anterior",
    nextPage: "Próxima página",
    closeDialog: "Fechar diálogo",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    filter: "Filtrar",
    sort: "Ordenar",
    moreOptions: "Mais opções",
    viewFile: "Visualizar arquivo",
    viewPaymentHistory: "Ver histórico de pagamento",
    evaluate: "Avaliar",
    copyPix: "Copiar chave PIX",
    paginationPrevious: "Go to previous page",
    paginationNext: "Go to next page",
    breadcrumb: "breadcrumb",
    pagination: "pagination",
    toggleSidebar: "Toggle Sidebar",
  },

  // Status values
  status: {
    active: "Ativo",
    inactive: "Inativo",
    pending: "Pendente",
    paid: "Pago",
    overdue: "Vencido",
    cancelled: "Cancelado",
    completed: "Concluído",
    inProgress: "Em andamento",
    sent: "Enviada",
    delivered: "Entregue",
    corrected: "Corrigida",
    notDelivered: "Não entregue",
    pendingEvaluation: "Avaliação pendente",
    evaluated: "Avaliada",
  },

  // Table-related strings
  table: {
    noResults: "Nenhum resultado encontrado.",
    showing: "Mostrando",
    of: "de",
    results: "resultados",
    page: "Página",
    previous: "Anterior",
    next: "Próxima",
    rowsPerPage: "Linhas por página",
    emptyState: "Nenhum registro encontrado.",
    paginationPrevious: "Previous",
    paginationNext: "Next",
    morePages: "More pages",
  },

  // Validation messages
  validation: {
    required: "Campo obrigatório.",
    emailInvalid: "Email inválido.",
    phoneInvalid: "Telefone inválido.",
    minLength: (n: number) => `Mínimo de ${n} caracteres.`,
    maxLength: (n: number) => `Máximo de ${n} caracteres.`,
    positiveNumber: "Deve ser um número positivo.",
    dateInvalid: "Data inválida.",
  },

  // Confirmation dialogs
  confirm: {
    deleteTitle: "Confirmar exclusão",
    deleteDescription: "Esta ação não pode ser desfeita.",
    irreversible: "Esta ação é irreversível.",
  },

  // App-level strings
  app: {
    name: "English School",
    copyright: (year: number) => `English School © ${year}`,
    tagline: "Manage your classes, track progress, and handle payments all in one place.",
    lgpd: "Conforme LGPD",
    developedBy: "Desenvolvido com",
    by: "por",
    developer: "Virtual Arrow",
    developerUrl: "https://virtualarrow.com.br",
  },

  // Toast notifications
  toasts: {
    success: "Operação realizada com sucesso!",
    error: "Ocorreu um erro. Tente novamente.",
    saved: "Salvo com sucesso!",
    deleted: "Excluído com sucesso!",
    updated: "Atualizado com sucesso!",
    created: "Criado com sucesso!",
    copied: "Copiado!",
    loading: "Carregando...",
    processing: "Processando...",
  },

  // Empty states
  emptyStates: {
    noResults: "Nenhum resultado encontrado",
    noResultsHint: "Ajuste os filtros acima ou limpe a busca",
    noData: "Nenhum dado disponível",
    noRecords: "Nenhum registro encontrado",
    searchEmpty: (query: string) => `Não encontramos resultados para "${query}". Tente ajustar os filtros ou termos de busca.`,
    filterEmpty: "Ajuste os filtros para ver os resultados.",
  },

  // Action-related strings (legacy, kept for compatibility)
  actions: {
    save: "Salvar",
    saving: "Salvando...",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Excluir",
    deleting: "Excluindo...",
    edit: "Editar",
    close: "Fechar",
    back: "Voltar",
    loading: "Carregando...",
    sending: "Enviando...",
    search: "Buscar",
    filter: "Filtrar",
    clear: "Limpar",
    add: "Adicionar",
    create: "Criar",
    update: "Atualizar",
    view: "Visualizar",
    download: "Baixar",
    copy: "Copiar",
    copied: "Copiado!",
    yes: "Sim",
    no: "Não",
    apply: "Aplicar",
  },
} as const;
