export const financial = {
  view: {
    title: "Financeiro",
    subtitle: "Gerencie cobranças e pagamentos",
    newButton: "Nova Cobrança",
    statTotal: "Total",
    statPaid: "Pago",
    statPending: "Pendente",
    statOverdue: "Vencido",
    statForecasted: "Previsto",
    forecastTitle: "Previsão de Faturamento Mensal",
    totalReceived: "Total recebido",
    totalToReceive: "Total a receber",
    pendingAndOverdue: "Pendentes + Em atraso",
    pendingLabel: "Pendente",
    overdueLabel: "Em atraso",
    errorLoading: "Erro ao carregar registros financeiros. Tente novamente.",
    colStudent: "Aluno",
    colClass: "Aula Vinculada",
    colAmount: "Valor",
    colMethod: "Método",
    colDueDate: "Vencimento",
    colStatus: "Status",
  },

  table: {
    colStudent: "Aluno",
    colAmount: "Valor",
    colDueDate: "Vencimento",
    colStatus: "Status",
    colPaymentMethod: "Pagamento",
    colActions: "Ações",
  },

  tableRow: {
    statusPaid: "Pago",
    statusPending: "Pendente",
    statusOverdue: "Atrasado",
    statusValidating: "Validando",
    statusAbonado: "Abonado",
    statusExtornado: "Extornado",
    statusCanceled: "Cancelado",
    noClass: "Sem aula vinculada",
    packageMonthly: "Pacote mensal",
    classes: "aula(s)",
    teacher: "Professor:",
    editedAt: "Editado em",
    absence: "Falta",
    grade: "Nota:",
    packageLabel: "(Pacote)",
    classDatePrefix: "Aula - ",
    undoing: "Desfazendo...",
    undo: "Desfazer",
    finalized: "Finalizado",
    confirm: "Confirmar",
    edit: "Editar",
    delete: "Excluir",
    viewHistory: "Ver histórico de pagamento",
    moreOptions: "Mais opções",
    chargeDone: "Cobrança finalizada",
  },

  formDialog: {
    titleNew: "Nova Cobrança",
    titleEdit: "Editar Cobrança",
    teacherLabel: "Professor *",
    teacherPlaceholder: "Selecione um professor (opcional)",
    teacherLinked: "Professor vinculado a esta cobrança",
    studentLabel: "Aluno *",
    studentPlaceholder: "Selecione um aluno",
    classLabel: "Aula Vinculada *",
    classSelectStudentFirst: "Selecione um aluno primeiro",
    classLoading: "Carregando aulas...",
    classNone: "Nenhuma aula disponível",
    classSelect: "Selecione uma aula",
    classNoneWithCharge:
      "Nenhuma aula disponível (todas já têm cobrança ou não há aulas cadastradas). Registre uma aula na aba Aulas primeiro.",
    amountLabel: "Valor (R$) *",
    amountPlaceholder: "1.450,00",
    dueDateLabel: "Data de Vencimento *",
    selectDate: "Selecione a data",
    descriptionLabel: "Descrição",
    descriptionPlaceholder: "Ex: Aulas de inglês - Janeiro/2025",
    paymentMethodLabel: "Método de Pagamento",
    paymentMethodPlaceholder: "Selecione (opcional)",
    pix: "PIX",
    card: "Cartão",
    cash: "Dinheiro",
    transfer: "Transferência",
    other: "Outro",
    cancel: "Cancelar",
    submitting: "Salvando...",
    saveChanges: "Salvar Alterações",
    create: "Criar Cobrança",
    classDatePrefix: "Aula - ",
    packageLabel: "(Pacote)",
    noClassLinked: "Sem aula vinculada",
    toasts: {
      success: "Cobrança criada com sucesso!",
      successEdit: "Cobrança atualizada com sucesso!",
      error: "Erro ao salvar cobrança.",
    },
  },

  confirmPaymentDialog: {
    title: "Confirmar pagamento",
    titleEarly: "Atenção: confirmar pagamento antecipado",
    descriptionEarly:
      "Esta cobrança está vinculada a uma aula que ainda não foi concluída.",
    description: (studentName: string, amount: string) =>
      `Deseja marcar como pago a cobrança de ${studentName} no valor de ${amount}?`,
    descriptionEarlyFull: (studentName: string, amount: string) =>
      `O pagamento já foi realizado? Ao confirmar, a cobrança de ${studentName} no valor de ${amount} será marcada como paga.`,
    confirmButton: "Confirmar Pagamento",
    processing: "Registrando...",
    cancel: "Cancelar",
    toasts: {
      success: "Pagamento confirmado com sucesso!",
      error: "Erro ao confirmar pagamento.",
    },
  },

  undoDialog: {
    title: "Desfazer cobrança",
    description: (studentName: string, amount: string) =>
      `Deseja desfazer o pagamento da cobrança de ${studentName} no valor de ${amount}?`,
    warningLinked:
      "Esta cobrança está vinculada a uma aula já concluída/confirmada. Deseja desfazer mesmo assim?",
    confirmButton: "Desfazer cobrança",
    processing: "Desfazendo...",
    cancel: "Cancelar",
    toasts: {
      success: "Pagamento desfeito com sucesso!",
      error: "Erro ao desfazer pagamento.",
    },
  },

  deleteDialog: {
    title: "Excluir cobrança",
    description: (studentName: string, amount: string) =>
      `Deseja excluir permanentemente a cobrança de ${studentName} no valor de ${amount}?`,
    irreversible: "Esta ação não pode ser desfeita.",
    confirmButton: "Excluir cobrança",
    deleting: "Excluindo...",
    cancel: "Cancelar",
    toasts: {
      success: "Cobrança excluída com sucesso!",
      error: "Erro ao excluir cobrança.",
    },
  },

  paymentHistoryDialog: {
    title: "Histórico de pagamento",
    noHistory: "Nenhum histórico disponível.",
    rejectionReason: "Comprovante inválido",
    descriptionLabel: "Descrição",
    proofLabel: "Comprovante de Pagamento",
    sentAt: "Enviado em",
    proofPending: "Aguardando aprovação",
    proofRejected: "Rejeitado:",
    noReason: "Sem motivo",
    view: "Ver",
    approve: "Aprovar",
    reject: "Rejeitar",
    confirmedBy: "Confirmado por",
    confirmedByRemoved: "Confirmado por (usuário removido)",
    paymentConfirmed: "Pagamento confirmado",
    dateUnavailable: "Data não disponível",
    noPayment: "Nenhum pagamento registrado para esta cobrança.",
    confirmPaymentButton: "Confirmar Pagamento",
    proofFilenameDefault: "Comprovante.pdf",
    toasts: {
      approveSuccess: "Pagamento confirmado!",
      approveError: "Erro ao aprovar comprovante",
      rejectSuccess: "Comprovante rejeitado",
      rejectError: "Erro ao rejeitar comprovante",
      proofOpenError: "Erro ao abrir comprovante",
    },
  },

  filters: {
    searchLabel: "Busca",
    searchPlaceholder: "Buscar por aluno...",
    statusLabel: "Status",
    statusAll: "Todos",
    statusPending: "Pendente",
    statusPaid: "Pago",
    statusOverdue: "Atrasado",
    statusValidating: "Validando",
    periodLabel: "Período",
    periodAll: "Todos",
    periodToday: "Hoje",
    periodWeek: "Esta semana",
    periodMonth: "Este mês",
    moreFilters: "Mais Filtros",
    clear: "Limpar",
    studentLabel: "Aluno",
    studentAll: "Todos os alunos",
    sortLabel: "Ordenar",
    sortDueAsc: "Vencimento (mais próximo)",
    sortDueDesc: "Vencimento (mais distante)",
    sortAmountDesc: "Valor (maior)",
    sortAmountAsc: "Valor (menor)",
    sortCreatedDesc: "Criação (mais recente)",
    sortCreatedAsc: "Criação (mais antiga)",
  },

  emptyState: {
    title: "Nenhuma cobrança encontrada",
    description: "Crie a primeira cobrança para um aluno.",
    actionLabel: "Nova cobrança",
    chargeCreationHint:
      "As cobranças são criadas ao registrar aulas. Registre uma aula na aba Aulas para gerar cobranças.",
    filterEmptyMessage: "Ajuste os filtros acima ou limpe a busca",
  },

  validation: {
    studentRequired: "Selecione um aluno",
    classLogRequired: "Selecione uma aula para vincular",
    amountRequired: "Informe o valor",
    dueDateRequired: "Informe a data de vencimento",
    dueDateFormat: "Formato deve ser dd/mm/aaaa",
    dueDateInvalid: "Data inválida",
    teacherRequired: "Selecione um professor",
  },
} as const;
