export const students = {
  view: {
    title: "Alunos",
    subtitle: "Gerencie seus alunos",
    newButton: "Novo Aluno",
    statTotal: "Total",
    statActive: "Ativos",
    statInactive: "Inativos",
    statNew: "Novos este mês",
  },

  formDialog: {
    titleNew: "Novo Aluno",
    titleEdit: "Editar Aluno",
    nameLabel: "Nome completo *",
    namePlaceholder: "Nome do aluno",
    emailLabel: "Email *",
    emailPlaceholder: "email@exemplo.com",
    phoneLabel: "Telefone *",
    phonePlaceholder: "(00) 00000-0000",
    hourlyRateLabel: "Valor por hora",
    hourlyRatePlaceholder: "Ex: 120,00",
    payDayLabel: "Dia de pagamento",
    payDayPlaceholder: "1 a 31",
    originLabel: "Origem *",
    originPlaceholder: "Como nos encontrou?",
    statusLabel: "Status",
    birthDateLabel: "Data de nascimento",
    birthDatePlaceholder: "dd/mm/aaaa",
    yearLabel: "Ano",
    yearPlaceholder: "Ano",
    countryLabel: "País *",
    stateLabel: "Estado/Região *",
    cityLabel: "Cidade *",
    teacherLabel: "Professor *",
    teacherPlaceholder: "Selecione um professor",
    paymentMethodLabel: "Método de pagamento",
    paymentMethodPlaceholder: "Selecione...",
    submitButton: "Salvar",
    submitting: "Salvando...",
    createButton: "Cadastrar",
    toasts: {
      success: "Aluno cadastrado com sucesso!",
      successEdit: "Aluno atualizado com sucesso!",
      error: "Erro ao salvar aluno.",
    },
  },

  archiveDialog: {
    titleArchive: "Confirmar arquivamento",
    titleReactivate: "Confirmar reativação",
    descriptionArchive: (name: string) =>
      `Tem certeza que deseja arquivar o aluno ${name}?`,
    archiveNote:
      "O histórico de aulas e cobranças será preservado. O aluno apenas não aparecerá mais nas listagens ativas.",
    descriptionReactivate: (name: string) =>
      `Tem certeza que deseja reativar o aluno ${name}? Ele voltará para a lista de ativos e terá o acesso reativado.`,
    confirmArchive: "Arquivar",
    confirmReactivate: "Reativar",
    archiving: "Arquivando...",
    reactivating: "Reativando...",
    importantLabel: "Importante:",
    toasts: {
      archiveSuccess: "Aluno arquivado com sucesso!",
      archiveError: "Erro ao arquivar aluno.",
      reactivateSuccess: "Aluno reativado com sucesso!",
      reactivateError: "Erro ao reativar aluno.",
    },
  },

  deleteDialog: {
    title: "Excluir definitivamente?",
    description: (name: string) =>
      `Os dados pessoais do aluno ${name} serão anonimizados (nome, e-mail, telefone). O histórico de aulas, atividades e cobranças será preservado. Esta ação não pode ser desfeita.`,
    warning:
      "A conta de acesso vinculada será removida do sistema. O e-mail ficará disponível para reutilização.",
    warningLabel: "Atenção:",
    confirmButton: "Excluir definitivamente",
    deleting: "Excluindo...",
    toasts: {
      success: "Aluno excluído com sucesso!",
      error: "Erro ao excluir aluno.",
      warnProfileNotDeleted:
        "Aluno removido. O perfil de usuário não pôde ser marcado como deletado.",
      warnAccountNotDeleted:
        "Aluno removido. A conta de acesso vinculada não pôde ser excluída — remova manualmente se necessário.",
    },
  },

  resetPasswordDialog: {
    title: "Redefinir senha do aluno",
    description: (name: string) =>
      `Nova senha para ${name}. Mínimo 6 caracteres.`,
    newPasswordLabel: "Nova senha",
    confirmPasswordLabel: "Confirmar senha",
    generateButton: "Gerar senha",
    submitButton: "Redefinir senha",
    submitting: "Redefinindo...",
    toasts: {
      minLength: "A senha deve ter no mínimo 6 caracteres.",
      mismatch: "As senhas não coincidem.",
      noAccount: "Este aluno não possui conta de acesso vinculada.",
      success: "Senha redefinida com sucesso!",
      error: "Erro ao redefinir senha.",
    },
  },

  detailSheet: {
    title: "Detalhes do Aluno",
    tabInfo: "Informações",
    tabClasses: "Aulas",
    tabFinancial: "Financeiro",
    tabActivities: "Atividades",
    infoSection: "Informações Pessoais",
    locationSection: "Localização",
    planSection: "Plano de aulas e cobrança",
    originSection: "Origem",
    originNotInformed: "Não informado",
    frequencyLabel: "Frequência",
    averageLabel: "Média",
    averageNote: "Nota geral",
    classesNote: "aulas",
    totalLabel: "Total",
    presentLabel: "Presenças",
    absenceLabel: "Faltas",
    classHistoryLabel: "Histórico de Aulas",
    noClassesMessage: "Nenhuma aula registrada",
    paidLabel: "Pago",
    pendingLabel: "Pendente",
    overdueLabel: "Atrasado",
    birthDateLabel: "Data de Nascimento",
    countryStateCity: "País - Estado - Cidade",
    hourlyRateLabel: "Valor por hora",
    classesPerWeekLabel: "Aulas por semana",
    monthlyTotalLabel: "Total mensal",
    paymentDayLabel: "Dia de pagamento",
    registeredAtLabel: "Cadastro em",
    lastEditedLabel: "Última edição em",
  },

  emptyState: {
    title: "Nenhum aluno encontrado",
    description: "Cadastre o primeiro aluno para começar.",
    actionLabel: "Novo aluno",
    toastCreated:
      "Aluno cadastrado! Um email com a senha foi enviado para o aluno.",
  },

  validation: {
    teacherRequired: "Selecione um professor",
    nameMin: "Nome deve ter pelo menos 2 caracteres",
    emailInvalid: "Email inválido",
    phoneRequired: "Telefone é obrigatório",
    phoneDigits: "Telefone deve ter entre 7 e 15 dígitos",
    payDayRange: "Dia de pagamento deve estar entre 1 e 31",
    hourlyRateRequired: "Valor por hora é obrigatório",
    payDayRequired: "Dia de pagamento é obrigatório",
    birthDateRequired: "Data de nascimento é obrigatória",
    birthDateInvalid: "Data inválida",
    countryRequired: "País é obrigatório",
    stateRequired: "Estado/Região é obrigatório",
    cityRequired: "Cidade é obrigatória",
  },

  table: {
    statusActive: "Ativo",
    statusInactive: "Inativo",
    statusAnonymized: "Anonimizado",
    filterAnonymized: "Anonimizados",
    editedAt: "Editado em",
    noCharges: "Sem cobranças",
    daysWithoutClass: (days: number) =>
      `${days} dia${days === 1 ? "" : "s"} sem aula`,
    colHourlyRate: "Valor/hora",
    colClasses: "Aulas",
    colMonthlyTotal: "Total mensal",
    colPaymentDay: "Dia pagto",
    colFinancial: "Financeiro",
  },

  locationSection: {
    countryLabel: "País *",
    stateLabel: "Estado (UF) *",
    stateManualLabel: "Estado/Região *",
    cityLabel: "Cidade *",
    selectCountry: "Selecione o país",
    selectState: "Selecione o estado",
    selectCity: "Selecione a cidade",
    selectStateFirst: "Selecione uma UF",
    noCitiesFound: "Nenhuma cidade encontrada.",
    noStatesFound: "Nenhum estado encontrado.",
    noCountriesFound: "Nenhum país encontrado.",
  },

  contactSection: {
    birthDateLabel: "Data de Nascimento",
    phoneLabel: "Telefone *",
    phoneInternational: "Ex: 555 123 4567",
    emailLabel: "Email *",
  },

  originOptions: {
    indicacao: "Indicação",
    google: "Google",
    instagram: "Instagram",
    passante: "Passante",
    outro: "Outro",
  },
  toasts: {
    created: "Aluno cadastrado com sucesso!",
    updated: "Aluno atualizado com sucesso!",
    archived: "Aluno arquivado e dados anonimizados (LGPD)",
    deleted: "Aluno excluído definitivamente.",
    restored: "Aluno restaurado com sucesso!",
    payDayUpdated: "Dia de pagamento atualizado com sucesso!",
  },
} as const;
