export const studentPortal = {
  home: {
    greeting: (name: string) => `Olá, ${name}! 👋`,
    subtitle: "Bom te ver por aqui",
    noProfile: "Perfil não vinculado",
    noProfileDescription:
      "Seu usuário ainda não está vinculado a um cadastro de aluno. Entre em contato com a secretaria.",
    financialOk: "Em dia",
    financialPending: "Pendente",
    financialOkDescription: "Você está em dia com seus pagamentos",
    financialPendingDescription: "Você tem pendências financeiras",
    financialLabel: "Situação Financeira",
    lastClassTitle: "Última Aula",
    noClasses: "Nenhuma aula registrada ainda",
    gradeLabel: "Nota",
    feedbackLabel: "Feedback:",
    totalClassesLabel: "Aulas realizadas",
    averageGradeLabel: "Média geral",
  },

  financial: {
    title: "Financeiro",
    subtitle: "Seus pagamentos e cobranças",
    financialStatusLabel: "Situação financeira",
    financialOk: "Em dia",
    financialPending: (count: number) => `${count} pendência${count !== 1 ? "s" : ""}`,
    financialOkDescription: "Nenhuma cobrança pendente",
    historyTitle: "Histórico de Pagamentos",
    noCharges: "Nenhuma cobrança registrada ainda",
    contactNote: "Dúvidas sobre pagamentos? Entre em contato com a secretaria.",
    loadError: "Erro ao carregar dados financeiros. Tente novamente.",
  },

  history: {
    title: "Histórico Acadêmico",
    subtitle: "Suas aulas e progresso",
    sectionTitle: "Histórico de Aulas",
    noHistory: "Nenhuma aula registrada ainda",
    noGrades: "Nenhuma aula com nota registrada.",
    noAbsences: "Nenhuma falta registrada.",
    tabClasses: "Aulas",
    tabAttendance: "Presença",
    tabGrades: "Média",
    totalClassesLabel: "Total de aulas",
    lastClassLabel: (date: string) => `Última aula: ${date}`,
    attendanceRateLabel: "Taxa de presença",
    totalAbsencesLabel: "Total de faltas",
    lastAbsenceLabel: "Última falta",
    missedClassesTitle: "Aulas faltadas",
    gradesSectionTitle: "Aulas com nota",
    averageGradeLabel: "Média geral",
    bestGradeLabel: "Melhor nota",
    worstGradeLabel: "Pior nota",
    statusFilterLabel: "Status:",
    sortLabel: "Ordenar:",
    statusOpen: "Em aberto",
    statusCompleted: "Concluídas",
    statusAll: "Todas",
    sortRecent: "Mais recente",
    sortOldest: "Mais antiga",
    loadError: "Erro ao carregar histórico. Tente novamente.",
    gradeLabel: "Nota",
    feedbackLabel: "Feedback",
    dateLabel: "Data",
  },

  activities: {
    title: "Minhas Atividades",
    subtitle: "Visualize e entregue as atividades enviadas pelo seu professor",
    sectionTitle: "Atividades",
    noActivities: "Nenhuma atividade encontrada",
    teacherLabel: (name: string) => `Professor: ${name}`,
    sentAt: (date: string) => `Enviada em ${date}`,
    dueDate: (date: string) => `Prazo: ${date}`,
    deliveredAt: (date: string) => `Entregue em ${date}`,
    correctedAt: (date: string) => `Corrigida em ${date}`,
    materialSection: "Material da atividade",
    deliverySection: "Sua entrega",
    feedbackSection: "Feedback do professor",
    uploadedFileLabel: "Arquivo que você enviou",
    correctionFileLabel: "Arquivo de correção",
    gradeLabel: "Nota:",
    gradeOutOf: "/ 10",
    deliverButton: "Entregar atividade",
    viewMore: "Ver mais",
    viewLess: "Ver menos",
    viewFileButton: "Ver arquivo",
    viewFileTitle: "Visualizar na web",
    downloadButton: "Baixar",
    toasts: {
      fileOpenError: "Não foi possível abrir o arquivo.",
      downloadPreparing: "Preparando download...",
      downloadSuccess: "Download concluído",
      downloadError: "Erro ao baixar arquivo",
      deliverSuccess: "Atividade entregue com sucesso!",
      deliverError: "Erro ao entregar atividade.",
    },
  },

  checkout: {
    title: "Pagamento",
    subtitle: "Confirme os dados e realize o pagamento",
    pixTitle: "Pagar via PIX",
    pixDescription: "Escaneie o QR Code ou copie a chave PIX",
    pixKeyLabel: "Chave PIX",
    copyKeyButton: "Copiar chave",
    keyCopied: "Chave copiada!",
    uploadProofTitle: "Enviar comprovante",
    uploadProofButton: "Enviar comprovante",
    uploadProofHint: "Envie o comprovante de pagamento para confirmação.",
    backButton: "Voltar",
    loadError: "Erro ao carregar dados. Tente novamente.",
  },

  classCard: {
    gradeLabel: "Nota",
    feedbackLabel: "Feedback",
    noFeedback: "Sem feedback",
    timeLabel: "Horário",
  },

  financialCard: {
    payButton: "Pagar",
    paidLabel: "Pago",
    overdueLabel: "Vencido",
    pendingLabel: "Pendente",
    dueDateLabel: "Vencimento",
    paidAtLabel: "Pago em",
  },
} as const;
